services:
  db:
    image: postgres:16
    container_name: expense-tracker-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: siman$69
      POSTGRES_DB: expense_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: